#! /usr/bin/env python
# -*- coding: utf-8 -*-
#python3

#инициализация
import telebot
import sqlite3
from threading import Thread
import requests
import json
import time
from SimpleQIWI import *


bot = telebot.TeleBot("-")

QIWI_TOKEN = '-'
QIWI_ACCOUNT = '-'
QIWI_LINK = '-'
QIWI_KART = '-'
api = QApi(token=QIWI_TOKEN, phone=QIWI_ACCOUNT)

#админы
admin = (646247390, 1204923521)



#обработчик базы
def ensure_connection(func):
    """ Декоратор для подключения к СУБД: открывает соединение,
        выполняет переданную функцию и закрывает за собой соединение.
        Потокобезопасно!
    """
    def inner(*args, **kwargs):
        with sqlite3.connect('telebot.db') as conn:
            kwargs['conn'] = conn
            res = func(*args, **kwargs)
        return res

    return inner


@ensure_connection
def init_db(conn, force: bool = False):
    """ Проверить что нужные таблицы существуют, иначе создать их

        Важно: миграции на такие таблицы вы должны производить самостоятельно!

        :param conn: подключение к СУБД
        :param force: явно пересоздать все таблицы
    """
    c = conn.cursor()

    # Информация о пользователе
    # TODO: создать при необходимости...

    # Сообщения от пользователей
    if force:
        c.execute('DROP TABLE IF EXISTS user_message')

    c.execute('''
        CREATE TABLE IF NOT EXISTS user_message (
            id          INTEGER PRIMARY KEY,
            user_id     INTEGER NOT NULL,
            ref_id      INTEGER NOT NULL,
            balance     INTEGER NOT NULL,
            ref_num     INTEGER NOT NULL,
            process     INTEGER NOT NULL,
            sale        INTEGER NOT NULL,
            phone       INTEGER NOT NULL,
            purchases   TEXT NOT NULL

        )
    ''')

    # Сохранить изменения
    conn.commit()


@ensure_connection
def add_record(conn, user_id: int, ref_id: int = 646247390, balance: int = 0, ref_num: int = 0, process: int = 0, sale:int = 0, phone:int = 0, purchases: str = ""):
    c = conn.cursor()
    c.execute('INSERT INTO user_message (user_id, ref_id, balance, ref_num, process, sale, phone, purchases) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', (user_id, ref_id, balance, ref_num, process, sale, phone, purchases))
    conn.commit()

@ensure_connection
def change_record(conn, user_id: int, sum: int,limit: int = 1):
    c = conn.cursor()
    c.execute('UPDATE user_message SET balance = balance + ' + str(sum) + ' WHERE user_id = ' + str(user_id))
    return c.fetchall()

@ensure_connection
def set_balanse(conn, user_id: int, sum: int,limit: int = 1):
    c = conn.cursor()
    c.execute('UPDATE user_message SET balance = ' + str(sum) + ' WHERE user_id = ' + str(user_id))
    return c.fetchall()

@ensure_connection
def set_ref(conn, user_id: int, ref_num: int,limit: int = 1):
    c = conn.cursor()
    c.execute('UPDATE user_message SET ref_num = ' + str(ref_num) + ' WHERE user_id = ' + str(user_id))
    return c.fetchall()

@ensure_connection
def set_phone(conn, user_id: int, phone: int,limit: int = 1):
    c = conn.cursor()
    c.execute('UPDATE user_message SET phone = ' + str(phone) + ' WHERE user_id = ' + str(user_id))
    return c.fetchall()

@ensure_connection
def add_ref(conn, user_id: int, limit: int = 1):
    c = conn.cursor()
    c.execute('UPDATE user_message SET ref_num = ref_num + 1 WHERE user_id = ' + str(user_id))
    return c.fetchall()

@ensure_connection
def list_record(conn, user_id: int, limit: int = 19):
    c = conn.cursor()
    c.execute('SELECT id,user_id,ref_id,balance,ref_num,process,sale,phone,purchases FROM user_message WHERE user_id = ? ORDER BY id DESC LIMIT ?', (user_id, limit))
    return c.fetchall()

@ensure_connection
def scerch_record(conn, user_id: int, limit: int = 19):
    c = conn.cursor()
    c.execute('SELECT id,user_id,ref_id,balance,ref_num,process,sale,phone,purchases FROM user_message WHERE user_id > ? ORDER BY id DESC LIMIT ?', (user_id, limit))
    return c.fetchall()

@ensure_connection
def check_record(conn, user_id: int, limit: int = 1):
    c = conn.cursor()
    c.execute('SELECT id FROM user_message WHERE user_id = ? ORDER BY id DESC LIMIT ?', (user_id, limit))
    return c.fetchall()

@ensure_connection
def rass(conn, user_id: int = 0, limit: int = 250000):
    c = conn.cursor()
    c.execute('SELECT user_id FROM user_message WHERE id > ? ORDER BY id DESC LIMIT ?', (user_id, limit))
    return c.fetchall()



def check_user(id):
    if check_record(user_id = id) == []:
        add_record(user_id = id)
        return 0


try:
    bot.send_message(1204923521, "Бот запущен", reply_markup = None)
except:
    pass

init_db()
#обработчик текста
@bot.message_handler(content_types = ["text"])




def handle_text(message):
    try:
        if message.text == "/start":
            check_user(message.chat.id)
            start_markup = telebot.types.ReplyKeyboardMarkup(True, True)
            start_markup.row("🗂 Каталог товаров","ℹ️ Как купить")

            bot.send_message(message.chat.id , "Привет " + message.chat.first_name + """
Это бот для покупки -
Информация о покупке в разделе 'Как купить' """, reply_markup = start_markup)


        elif message.text.find("/start") == 0:
            if check_record(user_id = message.chat.id) == []:
                add_record(user_id = message.chat.id, ref_id = message.text[7:])
                check_user(message.text[7:])
                add_ref(user_id = message.text[7:])
                bot.send_message(message.text[7:], "Пользователь перешёл по вашей реферальной ссылке", reply_markup = None)

            start_markup = telebot.types.ReplyKeyboardMarkup(True, True)
            start_markup.row("🗂 Каталог товаров","ℹ️ Как купить")


            bot.send_message(message.chat.id , "Привет " + message.chat.first_name + """
Это бот для покупки -
""", reply_markup = start_markup)


        elif (message.text.find("/ras") == 0) and (message.chat.id in admin):
            ras_text = message.text[4:]
            bot.send_message(message.chat.id , "Рассылка с текстом " + str(ras_text) + " запущенна", reply_markup = None)
            req = rass(user_id = 0)
            try:
                for i in range (5000):
                    try:
                        bot.send_message(req[i][0], ras_text, reply_markup = None)
                    except:
                        pass
            except:
                pass
            bot.send_message(message.chat.id , "Рассылка завершена", reply_markup = None)

        elif (message.text.find("/sbl") == 0) and (message.chat.id in admin):
            sbl_text = message.text.split()
            set_balanse(user_id = sbl_text[1], sum = sbl_text[2])
            bot.send_message(message.chat.id , "Пользавотелю с кодом " + str(sbl_text[1]) + " установлен баланс " +  str(sbl_text[2]), reply_markup = None)

        elif message.text == "/db" and (message.chat.id in admin):

            bot.send_message(message.chat.id , "Количество пользователей: " + str(scerch_record(user_id = 0)[0][0]), reply_markup = None)

        elif (message.text.find("/srf") == 0) and (message.chat.id in admin):
            srf_text = message.text.split()
            set_ref(user_id = srf_text[1], ref_num = srf_text[2])
            bot.send_message(message.chat.id , "Пользавотелю с кодом " + str(srf_text[1]) + " установлен количество рефералов " +  str(srf_text[2]), reply_markup = None)

        elif (message.text.find("/sms") == 0) and (message.chat.id in admin):
            srf_text = message.text.split()
            srf_text_sms = ""
            for i in range(len(srf_text) - 2):
                srf_text_sms = srf_text_sms + srf_text[i + 2]
                srf_text_sms = srf_text_sms + " "
            try:
                bot.send_message(srf_text[1] , str(srf_text_sms), reply_markup = None)
                bot.send_message(message.chat.id , "Пользователю с кодом " + str(srf_text[1]) + " Отправленно сообщение " +  str(srf_text_sms), reply_markup = None)
            except:
                bot.send_message(message.chat.id , "Проблема с отправкой", reply_markup = None)


        elif message.text.find("/set") == 0:
            check_record(user_id = message.chat.id)
            set_phone(user_id = message.chat.id, phone = message.text[5:])
            bot.send_message(message.chat.id, "Номер установлен", reply_markup = None)

        elif (message.text.find("/stats") == 0) and (message.chat.id in admin):
            check_record(user_id = message.chat.id)
            stats_req = list_record(user_id = message.text[7:])
            bot.send_message(message.chat.id, "Баланс: " + str(stats_req[0][3]) + """
Приведено рефералов: """ + str(stats_req[0][4]), reply_markup = None)

        if (message.text == "/balance") and (message.chat.id in admin):
            bot.send_message(message.chat.id , "На счету: " + str(api.balance[0]), reply_markup = None)


        elif message.text.find("/pay") == 0:
            check_record(user_id = message.chat.id)

            bot.send_message(message.chat.id, "Введите данные коректно", reply_markup = None)

        elif message.text == "/code":
            check_user(message.chat.id)
            bot.send_message(message.chat.id, message.chat.id, reply_markup = None)
        elif message.text == "🗂 Каталог товаров":
            check_user(message.chat.id)
            tovars_markup = telebot.types.InlineKeyboardMarkup()
            tovars_item1 = telebot.types.InlineKeyboardButton("- 99р 🔥", callback_data = "Private")


            tovars_markup.row(tovars_item1)


            bot.send_message(message.chat.id, "Выберите товар для покупки: ", reply_markup = tovars_markup)



        elif message.text == "ℹ️ Как купить":
            opicanie_markup = telebot.types.InlineKeyboardMarkup()
            opicanie_item = telebot.types.InlineKeyboardButton("Купить -", callback_data = "Private")

            opicanie_markup.row(opicanie_item)
            check_user(message.chat.id)
            bot.send_message(message.chat.id, """ Для покупки: Выбираем товар, выбираем необходимый способ оплаты, оплачиваем С УКАЗАНИЕМ своего айди телеграмма в коментарии к платежу.
Свой айди можно посмотреть в Настройки -> Имя пользователя. """, reply_markup = opicanie_markup)
    except Exception as e:
        try:
            bot.send_message(message.chat.id , "Ошибка на стороне сервера", reply_markup = None)
            bot.send_message(646247390, "Ошибка на стороне сервера", reply_markup = None)
            bot.send_message(646247390, str(repr(e)), reply_markup = None)
        except:
            pass






@bot.callback_query_handler(func=lambda call: True)
def callback_inline(call):
    try:
        if call.message:
            if call.data == "Menu":
                menu_markup = telebot.types.ReplyKeyboardMarkup(True, True)
                start_markup.row("🗂 Каталог товаров","ℹ️ Как купить")

                bot.delete_message(chat_id=call.message.chat.id, message_id=call.message.message_id)
                bot.send_message(call.message.chat.id , "Главная страница",reply_markup = menu_markup)



            if call.data == "Private":
                tovar_markup = telebot.types.InlineKeyboardMarkup()
                tovar_item1 = telebot.types.InlineKeyboardButton("Оплатить", callback_data = "pay_call11")
                tovar_item2 = telebot.types.InlineKeyboardButton("Назад", callback_data = "BackTovars")

                tovar_markup.row(tovar_item1)
                tovar_markup.row(tovar_item2)
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="""Приват

💰 Цена: 99 рублей

🚚 После оплаты с вами свяжутсу в течении нескольких часов и вы получите ссылку.

Внимание, указывайте свой уникальный айди в комментарии при оплате. """, reply_markup = tovar_markup)


            if call.data.find("pay_call") == 0:
                pay_call_id = call.data[8:]
                pay_call_markup = telebot.types.InlineKeyboardMarkup()
                pay_call_item1 = telebot.types.InlineKeyboardButton("Оплата QIWI 🥝", callback_data = "pay_qiwi" + str(pay_call_id))
                pay_call_item2 = telebot.types.InlineKeyboardButton("Оплата Сбербанк 💳", callback_data = "pay_sber" + str(pay_call_id))
                pay_call_item3 = telebot.types.InlineKeyboardButton("Оплата по ссылке 🏧", callback_data = "pay_link" + str(pay_call_id))

                pay_call_markup.row(pay_call_item1)
                pay_call_markup.row(pay_call_item2)
                pay_call_markup.row(pay_call_item3)
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Выберите способ оплаты",reply_markup=pay_call_markup)

            QIWI_ACCOUNT = '-'
            QIWI_LINK = '-'
            QIWI_KART = ' -'

            if call.data == "pay_link11":
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text=("Оплата по ссылке " + QIWI_LINK + """
цена: 99 рублей,
не забудьте указать свой уникальный айди в комментарии платежа. """  ), reply_markup=None)

            if call.data == "pay_qiwi11":
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text=("Оплата QIWI на счет " + QIWI_ACCOUNT + """
цена: 99 рублей,
не забудьте указать свой уникальный айди в комментарии платежа. """  ), reply_markup=None)

            if call.data == "pay_sber11":
                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text=("Оплата через банк " + QIWI_KART + """
цена: 99 рублей,
не забудьте указать свой уникальный айди в комментарии платежа. """ ), reply_markup=None)



            if call.data == "BackTovars":
                tovars_markup = telebot.types.InlineKeyboardMarkup()
                tovars_item1 = telebot.types.InlineKeyboardButton("- 99р 🔥", callback_data = "Private")


                tovars_markup.row(tovars_item1)

                bot.edit_message_text(chat_id=call.message.chat.id, message_id=call.message.message_id, text="Выберите товар для покупки: ", reply_markup=tovars_markup)



    except Exception as e:
        try:
            bot.send_message(message.chat.id , "Ошибка на стороне сервера", reply_markup = None)
            bot.send_message(1204923521, "Ошибка на стороне сервера", reply_markup = None)
            bot.send_message(1204923521, str(repr(e)), reply_markup = None)
        except:
            pass




#пуск бота
bot.polling(none_stop = True, interval = 0)
